-- Applied directly in production.
-- Version 20260502212831, name preorder_remaining_catalog.
-- This file exists so local history matches the production migration version.
-- The original statements were applied directly in production and are not stored here.
