-- Applied directly in production.
-- Version 20260502212806, name preorder_and_half_off.
-- This file exists so local history matches the production migration version.
-- The original statements were applied directly in production and are not stored here.
